### ISSUE TITLE
Issue with Ondato Library Installation on React Native ^0.72.0

### ISSUE THREAD

**Issue by martynas-petruska** [ondato/ondato-sdk-react-native#1]
Hi!

I'm encountering an issue while attempting to integrate the Ondato library into my React Native project with version ^0.72.0. I followed the documentation provided, but I'm currently stuck at the iOS build step.

## Problem:

The build process fails with the following error messages:

```
The following build commands failed:
SwiftCompile normal arm64 /Users/xxx/Projects/xxx/node_modules/ondato-sdk-react-native/ios/OSRN/OSRNViewManager.swift (in target 'ondato-sdk-react-native' from project 'Pods')
SwiftCompile normal arm64 Compiling\ OSRNViewManager.swift /Users/xxx/Projects/xxx/node_modules/ondato-sdk-react-native/ios/OSRN/OSRNViewManager.swift (in target 'ondato-sdk-react-native' from project 'Pods')
```

## Steps to Reproduce:

Cloned a new React Native project with version ^0.72.0.
Followed the Ondato library installation instructions from the official documentation.
Encountered the mentioned issues during the iOS build process.

## Additional Information:

- React Native Version: ^0.72.0
- Ondato Library Version: 2.4.1
- Xcode Version: 15.1
- macOS Version: 14.2.1
- Apple Silicon: M1 Pro

I've tried troubleshooting this problem on my own, but I can't seem to find a resolution. Could you please provide guidance on how to overcome this issue? Any help or suggestions would be greatly appreciated.

**Comment by Svaike** [comment]
@Lenovis we will try to reproduce the issue and will come back with answer most likely next week. How urgent is the matter?

**Comment by martynas-petruska** [comment]
> @Lenovis we will try to reproduce the issue and will come back with answer most likely next week. How urgent is the matter?

We made this flow by calling Ondato -> receiving `redirectUrl` -> calling `Linking` from `react-native` to open the website for authorization -> calling the redirect link, provided in the first place, to go back to the app with the deep link on success flow. For now, it's just a "nice to have feature" later on when we want to embed the Ondato flow in our app.

**Comment by Svaike** [comment]
@Lenovis just to confirm, did you follow this part of the integration guide?

> Comment out or remove the following line in your Podfile (the example is based on React Native 0.71.4 and might have variations on different versions), this is required because Flipper is currently not supported by Ondato SDK:
> 
>     # ...
>     #:flipper_configuration => flipper_config,
>     # ...

**Comment by Svaike** [comment]
@Lenovis the project was updated, please let me know if you still face the issue.

**Comment by martynas-petruska** [comment]
> @Lenovis the project was updated, please let me know if you still face the issue.

Hi, will check in the future.
