### ISSUE TITLE
Ondato SDK installation issue  

### ISSUE THREAD

**Issue by KhaledBaltaji** [ondato/ondato-sdk-react-native#3]
Hey team,

We have an issue with installing the SDK, while running the Pod Install stage.

Could you please guide us regarding the issue?

**Comment by Svaike** [comment]
Hi, @KhaledBaltaji,

could you specify what kind of error you're getting?

**Comment by Svaike** [comment]
If the error was related to OpenSSL you can get newest version of the project and test if it resolves your issue

**Comment by Svaike** [comment]
Also you can check app example: https://github.com/ondato/ondato-sdk-react-native/tree/main/example
