### ISSUE TITLE
An unexpected internal error occurred.

### ISSUE THREAD

**Issue by ajdobson** [ondato/ondato-sdk-react-native#5]
Hello 

We are using the react native SDK for identity verification.

We have done the first POST to get the identification ID and am using that in the config

    const config = {
        mode: 'test',
        identityVerificationId: 'a2fc57b0-e7e2-4a04-8d49-0b710f18c0e6',
        showSplashScreen: true,
        showStartScreen: false,
        showSelfieFrame: false,
        showSuccessWindow: false,
        skipRegistrationIfDriverLicense: false,
        showIdentificationWaitingScreen: false,
        simpleCustomization: {
            primaryColor: COLORS.primary,
            textColor: COLORS.dark,
            buttonTextColor: COLORS.light,
        },
    };
 
but seem to be getting this when doing `ondatoSdkRef.current?.open()`

LOG  {"load": {"identificationId": "a2fc57b0-e7e2-4a04-8d49-0b710f18c0e6"}, "message": "An unexpected internal error occurred.", "status": "Failed"}

Ive downloaded the example project and copied what its using and same thing.

Any ideas

**Comment by ajdobson** [comment]
FYI - I tried on the example project and its the same issue

**Comment by Svaike** [comment]
Hi @ajdobson, do you generate the new identification ID for each session? I can see that mentioned session was created yesterday and is already expired (unused session expire in 24h) and can only be started once.

**Comment by ajdobson** [comment]
Ok yeah that looks like it was the issue, we have slightly changed how we create the session. Thanks for quick reply!

**Comment by ajdobson** [comment]
Expired session
