### ISSUE TITLE
SDK closes by itself while opening in iOS

### ISSUE THREAD

**Issue by santoshiKumari28** [ondato/ondato-sdk-react-native#6]
sdk is working fine in android but when I try to open it in iOS device it closes automatiucally without any error. Using sdk version 2.5.3
We got following logs in state:

{"load": {"identificationId": "b9a7e101-2bfc-4b16-a45f-4eda6a462660"}, "message": "An unexpected internal error occurred.", "status": "Failed"}

**Comment by Svaike** [comment]
Hi @santoshiKumari28,

when was b9a7e101-2bfc-4b16-a45f-4eda6a462660 session created? Keep in mind that in the sandbox environment data is hard deleted after 7days and for each user session a new IDV ID must be created.

**Comment by antiergit** [comment]
@Svaike we are creating a new session every time we try to open sdk and also it is working fine for android, so the issue must be something else.

**Comment by Svaike** [comment]
@antiergit @santoshiKumari28 I think I found the reason: you've created b9a7e101-2bfc-4b16-a45f-4eda6a462660 session in the production environment, but tried to start the user flow in the sandbox.

**Comment by santoshiKumari28** [comment]
Thanks @Svaike. This resolved the issue.

> @antiergit @santoshiKumari28 I think I found the reason: you've created b9a7e101-2bfc-4b16-a45f-4eda6a462660 session in the production environment, but tried to start the user flow in the sandbox.
