### ISSUE TITLE
Stuck on Uploading Information Status

### ISSUE THREAD

**Issue by AbhishekDev1112** [ondato/ondato-sdk-react-native#9]
Ondato is displaying the uploading information status in the Android app and not proceeding to the next step for the KYC process.
I use version 2.5.4 of the Ondato platform. I attached the video for reference.

https://github.com/user-attachments/assets/925549be-0799-4205-9814-67ed43a1dec6

**Comment by Svaike** [comment]
@AbhishekDev1112 can you test if you can reproduce the issue with the latest version? Also for each new session you need to use a new session id. If the issue persists please share the session ID and we'll check the BE logs.
